name: Build Docker Image
permissions: {}

on:
  push:
    branches: main

jobs:
  build:
    uses: docker/github-builder-experimental/.github/workflows/build.yml@main
    permissions:
      contents: read # same as global permissions
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # required to push to GHCR
    with:
      platform: linux/amd64,linux/arm64
      output: image
      push: true
      meta-images: |
        ghcr.io/dfunkt/cloudflared
      meta-tags: |
        type=raw,value=latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    needs: build
    if: ${{ vars.WEBHOOK_ENABLED == 'true' }}

    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@2381f0e9c7b6bf061fb1405bd0804b8706116369 # v3.0.8
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
